// @ts-nocheck
/* eslint-disable */
/**
 * ⚠️ DO NOT MODIFY THIS FILE BY HAND! ⚠️
 * It was auto-generated from the megaprofile api OAS json schema.
 * If you need to make changes, update the json schema api and re-run the generation script:
 * > npm run megaprofile:generate
 */
import {
  AddressType,
  Affiliation,
  DisplayConstituentType,
  SalesforceConstituentType,
  DataSource,
  CareerSupportOffered,
  CareerSupportInterests1,
  CommunityAffinity,
  CommunityAffinity_2,
  SuffixProfessional,
  Prefix,
  EmailType,
  SuffixPersonal,
  PhoneNumberType,
  MaritalStatus,
  SelfReportedEthnicity,
  ConstituentStatus,
  LegalEntity,
  DegreeCertificate,
  DegreeLevel,
  InterestDescription,
  ProficiencyLevel,
  Type,
  AffiliationType,
  FamilyRelationshipType,
  Category,
  ParticipationType,
  UrlType,
} from './types';

export const addressTypeOptions: AddressType[] = [
  "Home",
  "Business"
];
export const affiliationOptions: Affiliation[] = [
  "GSB Alum",
  "GSB SEP",
  "GSB Life Member",
  "GSB Student",
  "GSB Faculty",
  "GSB Staff",
  "GSB Defined Alums and Students",
  "Friend",
  "SAA Email",
  "Student",
  "Non-Student",
  "SAA Alum",
  "Med CRT Graduate",
  "Med Alum",
  "Med Student",
  "Law Alum",
  "Law Student",
  "EDU Alum",
  "EDU Student"
];
export const displayConstituentTypeOptions: DisplayConstituentType[] = [
  "Alumni",
  "Faculty",
  "Organization",
  "Former Student",
  "Grandparent",
  "Friend",
  "Student",
  "Staff",
  "Postgraduate Study",
  "Parent"
];
export const salesforceConstituentTypeOptions: SalesforceConstituentType[] = [
  "Grad Alum",
  "Parent UG",
  "Grad Student",
  "Corporate Foundation",
  "UG Alum",
  "Hosp Staff",
  "Univ Staff",
  "Grandparent",
  "Professional Foundation",
  "Non-Grad",
  "Friend",
  "Personal Foundation",
  "Estate - Trust",
  "UG Student",
  "Cert Holder",
  "Faculty",
  "Corporation",
  "UG & Grad Alum",
  "Association",
  "Estate - Outright",
  "Personal Corporation"
];
export const dataSourceOptions: DataSource[] = [
  "LinkedIn",
  "Web Profile/Registration"
];
export const careerSupportOfferedOptions: CareerSupportOffered[] = [
  "Yes",
  "No",
  "Graduate or Professional School Only"
];
export const careerSupportInterestsOptions: CareerSupportInterests1[] = [
  "Provide career advice",
  "Advise on industry and function trends",
  "Help in navigating diversity in career and life",
  "Mentor students or young alumni",
  "Assist in job, internship, project or job shadowing opportunities",
  "Provide graduate or professional school advice",
  "Facilitate informational interviewing, networking",
  "Conduct mock interviews, critique elevator pitches",
  "Consider speaking opportunities (e.g., panels)",
  "Engage in academic collaborations"
];
export const communityAffinityOptions: CommunityAffinity[] = [
  "Military Veteran",
  "First-generation and/or Low-income",
  "LGBTQ+",
  "Disabled",
  "Neurodiverse",
  "Indigenous or Native",
  "Asian/Pacific Islander",
  "Latino/a/x",
  "Black",
  "Women's Communities",
  "Baha'i",
  "Buddhist",
  "Christian",
  "Hindu",
  "Jewish",
  "Muslim",
  "Sikh"
];
export const communityAffinity_2Options: CommunityAffinity_2[] = [
  "Military Veteran",
  "First-generation and/or Low-income",
  "LGBTQ+",
  "Disabled",
  "Neurodiverse",
  "Indigenous or Native",
  "Asian/Pacific Islander",
  "Latino/a/x",
  "Black",
  "Women's Communities",
  "Baha'i",
  "Buddhist",
  "Christian",
  "Hindu",
  "Jewish",
  "Muslim",
  "Sikh"
];
export const suffixProfessionalOptions: SuffixProfessional[] = [
  "AIA",
  "CFA",
  "CPA",
  "DC",
  "DD",
  "DDS",
  "DMD",
  "DMin",
  "DO",
  "DVM",
  "EdD",
  "Emerita",
  "Emeritus",
  "Esq.",
  "JD",
  "LCSW",
  "LICSW",
  "LLB",
  "LLD",
  "M ARCH",
  "MA",
  "MBA",
  "MD",
  "MFA",
  "MFT",
  "MLA",
  "MP",
  "MPH",
  "MS",
  "MSM",
  "MSW",
  "OBE",
  "OD",
  "PE",
  "PhD",
  "Pharm D",
  "Ret.",
  "RN",
  "SJ",
  "USA",
  "USAF",
  "USAFR",
  "USAR",
  "USCG",
  "USCGR",
  "USMC",
  "USMCR",
  "USN",
  "USNR",
  "USA, Ret.",
  "USAF, Ret.",
  "USAFR, Ret.",
  "USAR, Ret.",
  "USCG, Ret.",
  "USCGR, Ret.",
  "USMC, Ret.",
  "USMCR, Ret.",
  "USN, Ret.",
  "USNR, Ret."
];
export const prefixOptions: Prefix[] = [
  "Mr.",
  "Ms.",
  "Mrs.",
  "Miss",
  "Mr/s.",
  "Mx.",
  "Dr.",
  "Admiral",
  "Captain",
  "Colonel",
  "Commander",
  "General",
  "Lieutenant",
  "Lieutenant Colonel",
  "Major",
  "Professor",
  "Rabbi",
  "The Honorable",
  "The Reverend"
];
export const emailTypeOptions: EmailType[] = [
  "Business Email",
  "GSB Email",
  "Home Email",
  "Other Email",
  "SAA Email"
];
export const suffixPersonalOptions: SuffixPersonal[] = [
  "Jr.",
  "Sr.",
  "II",
  "III",
  "IV"
];
export const phoneNumberTypeOptions: PhoneNumberType[] = [
  "Business Phone",
  "Home Phone",
  "Mobile"
];
export const maritalStatusOptions: MaritalStatus[] = [
  "Married",
  "Widowed",
  "Single",
  "Domestic Partnered",
  "Marital Unknown",
  "Married At Death",
  "Formerly Married/Partnered"
];
export const selfReportedEthnicityOptions: SelfReportedEthnicity[] = [
  "Custom Self-Identified Race/Ethnicity",
  "American Indian or Alaska Native",
  "Asian",
  "Black or African American",
  "Hispanic or Latino",
  "Native Hawaiian or Other Pacific Islander",
  "White",
  "Decline to State",
  "Chinese",
  "Filipino",
  "Japanese",
  "Korean",
  "Latin/Latino",
  "Mexican/Chicano",
  "Puerto Rican",
  "South Asian",
  "Vietnamese",
  "American Indian (Canada)",
  "American Indian (Central/South)",
  "Pacific Islander",
  "White (European)",
  "White (Middle Eastern)",
  "White (North African)"
];
export const constituentStatusOptions: ConstituentStatus[] = [
  "Deceased",
  "Active"
];
export const legalEntityOptions: LegalEntity[] = [
  "Person"
];
export const degreeCertificateOptions: DegreeCertificate[] = [
  "01 - Other non-Stanford Undergraduate Degree",
  "02 - Other non-Stanford Masters Degree",
  "03 - Other non-Stanford Doctoral Degree",
  "AB - Bachelor of Arts",
  "AM - Master of Arts",
  "BA - Bachelor of Arts",
  "BAR - Bachelor of Architecture",
  "BAS - Bachelor of Arts & Science",
  "B - Bachelor Undeclared",
  "BS - Bachelor of Science",
  "BSN - Bachelor of Science in Nursing",
  "CRT - Certificate Program",
  "DDS - Doctor of Dental Science",
  "DMA - Doctor of Musical Arts",
  "DMD - Doctor of Dental Medicine",
  "DNP - Doctor of Nursing Practice",
  "DO - Doctor of Osteopathic Medicine",
  "DPM - Doctor of Podiatric Medicine",
  "DVM - Doctor of Veterinary Medicine",
  "EDD - Doctor of Education",
  "EDM - Master of Education",
  "EDS - Educational Specialist",
  "ENG - Engineer",
  "IA - Industrial Administration",
  "JD - Doctor of Jurisprudence",
  "JM - Master of Jurisprudence",
  "JSD - Doctor of the Science of Law",
  "JSM - Master of Science of Law",
  "LLB - Bachelor of Laws",
  "LLM - Master of Laws",
  "MA - Master of Arts",
  "MAR - Master of Architecture",
  "MAT - Master of Arts in Teaching",
  "MBA - Master of Business Administration",
  "MCRP - Master of City and Regional Planning",
  "MD - Doctor of Medicine",
  "MDIV - Master of Divinity",
  "MEA - Master of Education Administration",
  "MFA - Master of Fine Arts",
  "MF - Med Fellow",
  "MLA - Master of Liberal Arts",
  "MLIS - Master of Library and Information Science",
  "MLS - Master of Legal Studies",
  "MPA - Master of Public Administration",
  "MPH - Master of Public Health",
  "MPP - Master of Public Policy",
  "MRP - Master of Regional Planning",
  "MSD - Master of Scientific Didactics",
  "MS - Master of Science",
  "MSM - Master of Science in Management",
  "MSN - Master of Science in Nursing",
  "MSW - Master of Social Work",
  "PD - PostDoc",
  "PHD - Doctor of Philosophy",
  "RN - Registered Nurse",
  "SLN-Sloan"
];
export const degreeLevelOptions: DegreeLevel[] = [
  "1 - Undergraduate",
  "2 - Masters",
  "3 - Doctoral",
  "4 - Certificate"
];
export const interestOptions: InterestDescription[] = [
  "3D Printing",
  "Acting",
  "Aerospace",
  "Agriculture",
  "Aikido",
  "Algorithms",
  "Analytics",
  "Animals",
  "Animation",
  "Antiques",
  "Archery",
  "Architecture",
  "Art",
  "Artificial Intelligence",
  "Asia",
  "Astronomy",
  "Astrophysics",
  "Athletics",
  "Aviation",
  "Ayurveda",
  "Backpacking",
  "Badminton",
  "Baking",
  "Ballet",
  "Banking",
  "Baseball",
  "Basketball",
  "BBQ",
  "Beer",
  "Bicycling",
  "Biking",
  "Biotechnology",
  "Birdwatching",
  "Black Lives Matter",
  "Blockchain",
  "Blogging",
  "Board Games",
  "Boating",
  "Bodysurfing",
  "Bonsai",
  "Books",
  "Bouldering",
  "Bowhunting",
  "Bowling",
  "Boy Scouts",
  "Brazil",
  "Brewing",
  "Bridge",
  "Buddhism",
  "Burning Man",
  "Business Development",
  "Calligraphy",
  "Camping",
  "Canoeing",
  "Carpentry",
  "Cars",
  "Cartooning",
  "Cats",
  "Cello",
  "Charity",
  "Chemistry",
  "Chess",
  "China",
  "Christianity",
  "Church",
  "Cinema",
  "Clarinet",
  "Climate Change",
  "Climbing",
  "Cloud Computing",
  "Coaching",
  "Coffee",
  "Comedy",
  "Community Service",
  "Computer Science",
  "Computers",
  "Concerts",
  "Conservation",
  "Consulting",
  "Cooking",
  "Costuming",
  "Creative Writing",
  "Cricket",
  "Crossfit",
  "Crosswords",
  "Culture",
  "Cybersecurity",
  "Cycling",
  "Dancing",
  "Deep Learning",
  "Design",
  "Dining",
  "Diplomacy",
  "Diversity",
  "Diving",
  "DJing",
  "Dog Training",
  "Dogs",
  "Drawing",
  "Driving",
  "Drumming",
  "eCommerce",
  "Ecology",
  "Economics",
  "Education",
  "Energy",
  "Entrepreneurship",
  "Environment",
  "Equestrian",
  "Ethics",
  "Evolution",
  "Exercise",
  "Faith",
  "Family",
  "Fashion",
  "Feminism",
  "Fencing",
  "Fiction",
  "Figure Skating",
  "Finance",
  "Fishing",
  "Fitness",
  "Flute",
  "Fly Fishing",
  "Flying",
  "Food",
  "Football",
  "France",
  "Fundraising",
  "Game Theory",
  "Gaming",
  "Gardening",
  "Gastronomy",
  "Genealogy",
  "General Management",
  "Genetics",
  "Genomics",
  "Geocaching",
  "Geology",
  "Germany",
  "Golf",
  "Government",
  "Grilling",
  "Guitar",
  "Health",
  "Healthcare",
  "High Tech",
  "Hiking",
  "History",
  "HIV/AIDS",
  "Hockey",
  "Horses",
  "Horticulture",
  "Human Rights",
  "Humor",
  "Hunting",
  "Ice Hockey",
  "Illustration",
  "Improv",
  "Inline Skating",
  "Innovation",
  "Insurance",
  "International Development",
  "International Relations",
  "International Travel",
  "Internet",
  "Investing",
  "Jazz",
  "Jogging",
  "Journalism",
  "Judaism",
  "Judo",
  "Juggling",
  "Karaoke",
  "Karate",
  "Kayaking",
  "Kendo",
  "Kickboxing",
  "Kitesurfing",
  "Knitting",
  "Krav Maga",
  "Lgbtq+",
  "Lacrosse",
  "Languages",
  "Latin America",
  "Law",
  "Leadership",
  "Linguistics",
  "Literature",
  "Litigation",
  "Logistics",
  "Machine Learning",
  "Maintenance",
  "Marathon",
  "Marketing",
  "Martial Arts",
  "Mathematics",
  "Media",
  "Medical Devices",
  "Medicial Devices",
  "Medicine",
  "Meditation",
  "Mentoring",
  "Metaphysics",
  "Meteorology",
  "Middle East",
  "Military",
  "Mindfulness",
  "Minority Rights",
  "Motorcycles",
  "Mountain Biking",
  "Mountain Climbing",
  "Mountaineering",
  "Movies",
  "Museums",
  "Music",
  "Musical Theater",
  "Nanobiotechnology",
  "Nanocomposites",
  "Nanoelectronics",
  "Nanofabrication",
  "Nanomaterials",
  "Nanomedicine",
  "Nanoparticles",
  "Nanopattering",
  "Nanophotonics",
  "Nanoscience",
  "Nanostructures",
  "Nanotechnology",
  "Nanotoxicity",
  "Nanotoxicity",
  "Nature",
  "Needlepoint",
  "Networking",
  "Neuroscience",
  "Nonprofit",
  "Nutrition",
  "Opera",
  "Optics",
  "Optimization",
  "Orchids",
  "Organizational Behavior",
  "Origami",
  "Outdoors",
  "Painting",
  "Paragliding",
  "Parenting",
  "Percussion",
  "Permaculture",
  "Pets",
  "Philanthropy",
  "Philosophy",
  "Photography",
  "Physics",
  "Piano",
  "Pilates",
  "Ping Pong",
  "Plants",
  "Poetry",
  "Poker",
  "Policy",
  "Politics",
  "Polo",
  "Privacy",
  "Product Management",
  "Psychiatry",
  "Psychology",
  "Public Speaking",
  "Publishing",
  "Python",
  "Quantum Physics",
  "Quilting",
  "Racquetball",
  "Railroads",
  "Reading",
  "Real Estate",
  "Religion",
  "Remote Sensing",
  "Research",
  "Retail",
  "Robotics",
  "Rollerblading",
  "Rotary",
  "Rowing",
  "Rugby",
  "Running",
  "Sailing",
  "Science",
  "Science Fiction",
  "Screenwriting",
  "Scuba Diving",
  "Sculpture",
  "Sewing",
  "Shakespeare",
  "Shopping",
  "Singing",
  "Skateboarding",
  "Skiing",
  "Skydiving",
  "Snorkeling",
  "Snowboarding",
  "Soccer",
  "Social Justice",
  "Social Media",
  "Sociology",
  "Softball",
  "Software Development",
  "Solar Energy",
  "Songwriting",
  "Spinning",
  "Spirituality",
  "Sports",
  "Squash",
  "Statistics",
  "Stocks",
  "Strategy",
  "Surfing",
  "Sustainability",
  "Swimming",
  "Tae Kwon Do",
  "Teaching",
  "Technology",
  "Television",
  "Tennis",
  "Theater",
  "Theology",
  "Travel",
  "Trekking",
  "Triathlon",
  "Trivia",
  "Trumpet",
  "Ultimate Frisbee",
  "Veganism",
  "Venture Capital",
  "Video Games",
  "Viola",
  "Violin",
  "Volleyball",
  "Volunteering",
  "Wakeboarding",
  "Walking",
  "Water Polo",
  "Waterskiing",
  "Weight Training",
  "White Water Rafting",
  "Wildlife",
  "Windsurfing",
  "Wine",
  "Woodworking",
  "Wrestling",
  "Writing",
  "Yachting",
  "Yoga"
];
export const interestDescriptionOptions: InterestDescription[] = [
  "3D Printing",
  "Acting",
  "Aerospace",
  "Agriculture",
  "Aikido",
  "Algorithms",
  "Analytics",
  "Animals",
  "Animation",
  "Antiques",
  "Archery",
  "Architecture",
  "Art",
  "Artificial Intelligence",
  "Asia",
  "Astronomy",
  "Astrophysics",
  "Athletics",
  "Aviation",
  "Ayurveda",
  "Backpacking",
  "Badminton",
  "Baking",
  "Ballet",
  "Banking",
  "Baseball",
  "Basketball",
  "BBQ",
  "Beer",
  "Bicycling",
  "Biking",
  "Biotechnology",
  "Birdwatching",
  "Black Lives Matter",
  "Blockchain",
  "Blogging",
  "Board Games",
  "Boating",
  "Bodysurfing",
  "Bonsai",
  "Books",
  "Bouldering",
  "Bowhunting",
  "Bowling",
  "Boy Scouts",
  "Brazil",
  "Brewing",
  "Bridge",
  "Buddhism",
  "Burning Man",
  "Business Development",
  "Calligraphy",
  "Camping",
  "Canoeing",
  "Carpentry",
  "Cars",
  "Cartooning",
  "Cats",
  "Cello",
  "Charity",
  "Chemistry",
  "Chess",
  "China",
  "Christianity",
  "Church",
  "Cinema",
  "Clarinet",
  "Climate Change",
  "Climbing",
  "Cloud Computing",
  "Coaching",
  "Coffee",
  "Comedy",
  "Community Service",
  "Computer Science",
  "Computers",
  "Concerts",
  "Conservation",
  "Consulting",
  "Cooking",
  "Costuming",
  "Creative Writing",
  "Cricket",
  "Crossfit",
  "Crosswords",
  "Culture",
  "Cybersecurity",
  "Cycling",
  "Dancing",
  "Deep Learning",
  "Design",
  "Dining",
  "Diplomacy",
  "Diversity",
  "Diving",
  "DJing",
  "Dog Training",
  "Dogs",
  "Drawing",
  "Driving",
  "Drumming",
  "eCommerce",
  "Ecology",
  "Economics",
  "Education",
  "Energy",
  "Entrepreneurship",
  "Environment",
  "Equestrian",
  "Ethics",
  "Evolution",
  "Exercise",
  "Faith",
  "Family",
  "Fashion",
  "Feminism",
  "Fencing",
  "Fiction",
  "Figure Skating",
  "Finance",
  "Fishing",
  "Fitness",
  "Flute",
  "Fly Fishing",
  "Flying",
  "Food",
  "Football",
  "France",
  "Fundraising",
  "Game Theory",
  "Gaming",
  "Gardening",
  "Gastronomy",
  "Genealogy",
  "General Management",
  "Genetics",
  "Genomics",
  "Geocaching",
  "Geology",
  "Germany",
  "Golf",
  "Government",
  "Grilling",
  "Guitar",
  "Health",
  "Healthcare",
  "High Tech",
  "Hiking",
  "History",
  "HIV/AIDS",
  "Hockey",
  "Horses",
  "Horticulture",
  "Human Rights",
  "Humor",
  "Hunting",
  "Ice Hockey",
  "Illustration",
  "Improv",
  "Inline Skating",
  "Innovation",
  "Insurance",
  "International Development",
  "International Relations",
  "International Travel",
  "Internet",
  "Investing",
  "Jazz",
  "Jogging",
  "Journalism",
  "Judaism",
  "Judo",
  "Juggling",
  "Karaoke",
  "Karate",
  "Kayaking",
  "Kendo",
  "Kickboxing",
  "Kitesurfing",
  "Knitting",
  "Krav Maga",
  "Lgbtq+",
  "Lacrosse",
  "Languages",
  "Latin America",
  "Law",
  "Leadership",
  "Linguistics",
  "Literature",
  "Litigation",
  "Logistics",
  "Machine Learning",
  "Maintenance",
  "Marathon",
  "Marketing",
  "Martial Arts",
  "Mathematics",
  "Media",
  "Medical Devices",
  "Medicial Devices",
  "Medicine",
  "Meditation",
  "Mentoring",
  "Metaphysics",
  "Meteorology",
  "Middle East",
  "Military",
  "Mindfulness",
  "Minority Rights",
  "Motorcycles",
  "Mountain Biking",
  "Mountain Climbing",
  "Mountaineering",
  "Movies",
  "Museums",
  "Music",
  "Musical Theater",
  "Nanobiotechnology",
  "Nanocomposites",
  "Nanoelectronics",
  "Nanofabrication",
  "Nanomaterials",
  "Nanomedicine",
  "Nanoparticles",
  "Nanopattering",
  "Nanophotonics",
  "Nanoscience",
  "Nanostructures",
  "Nanotechnology",
  "Nanotoxicity",
  "Nanotoxicity",
  "Nature",
  "Needlepoint",
  "Networking",
  "Neuroscience",
  "Nonprofit",
  "Nutrition",
  "Opera",
  "Optics",
  "Optimization",
  "Orchids",
  "Organizational Behavior",
  "Origami",
  "Outdoors",
  "Painting",
  "Paragliding",
  "Parenting",
  "Percussion",
  "Permaculture",
  "Pets",
  "Philanthropy",
  "Philosophy",
  "Photography",
  "Physics",
  "Piano",
  "Pilates",
  "Ping Pong",
  "Plants",
  "Poetry",
  "Poker",
  "Policy",
  "Politics",
  "Polo",
  "Privacy",
  "Product Management",
  "Psychiatry",
  "Psychology",
  "Public Speaking",
  "Publishing",
  "Python",
  "Quantum Physics",
  "Quilting",
  "Racquetball",
  "Railroads",
  "Reading",
  "Real Estate",
  "Religion",
  "Remote Sensing",
  "Research",
  "Retail",
  "Robotics",
  "Rollerblading",
  "Rotary",
  "Rowing",
  "Rugby",
  "Running",
  "Sailing",
  "Science",
  "Science Fiction",
  "Screenwriting",
  "Scuba Diving",
  "Sculpture",
  "Sewing",
  "Shakespeare",
  "Shopping",
  "Singing",
  "Skateboarding",
  "Skiing",
  "Skydiving",
  "Snorkeling",
  "Snowboarding",
  "Soccer",
  "Social Justice",
  "Social Media",
  "Sociology",
  "Softball",
  "Software Development",
  "Solar Energy",
  "Songwriting",
  "Spinning",
  "Spirituality",
  "Sports",
  "Squash",
  "Statistics",
  "Stocks",
  "Strategy",
  "Surfing",
  "Sustainability",
  "Swimming",
  "Tae Kwon Do",
  "Teaching",
  "Technology",
  "Television",
  "Tennis",
  "Theater",
  "Theology",
  "Travel",
  "Trekking",
  "Triathlon",
  "Trivia",
  "Trumpet",
  "Ultimate Frisbee",
  "Veganism",
  "Venture Capital",
  "Video Games",
  "Viola",
  "Violin",
  "Volleyball",
  "Volunteering",
  "Wakeboarding",
  "Walking",
  "Water Polo",
  "Waterskiing",
  "Weight Training",
  "White Water Rafting",
  "Wildlife",
  "Windsurfing",
  "Wine",
  "Woodworking",
  "Wrestling",
  "Writing",
  "Yachting",
  "Yoga"
];
export const proficiencyLevelOptions: ProficiencyLevel[] = [
  "ELEMENTARY",
  "NATIVE_OR_BILINGUAL",
  "FULL_PROFESSIONAL",
  "LIMITED_WORKING",
  "PROFESSIONAL_WORKING",
  "NONE"
];
export const typeOptions: Type[] = [
  "Advisory Board Member",
  "Board Member",
  "Business Association",
  "Consultant",
  "Employee",
  "Intern",
  "Founder",
  "Owner",
  "Part-Time Employee",
  "Volunteer",
  "Stanford University Faculty",
  "Stanford University Hospital Staff",
  "Stanford University Staff",
  "Stanford University Fellow"
];
export const affiliationTypeOptions: AffiliationType[] = [
  "Alum",
  "Current Student",
  "Faculty",
  "Parent of Undergraduate Student",
  "Staff"
];
export const familyRelationshipTypeOptions: FamilyRelationshipType[] = [
  "Child",
  "Spouse/Partner",
  "Parent",
  "Cousin",
  "Grandparent",
  "Grandchild",
  "Aunt/Uncle",
  "Niece/Nephew",
  "Great Grandchild",
  "Great Grandparent",
  "Relative",
  "Sibling",
  "Significant Other",
  "Step-child",
  "Step-parent",
  "Guest"
];
export const categoryOptions: Category[] = [
  "Business School",
  "Club Sports",
  "Eating Clubs",
  "Fraternities",
  "Fundraising",
  "Haas Ctr",
  "Law School",
  "Miscellaneous",
  "Overseas Studies",
  "Performing Arts",
  "Sororities"
];
export const participationTypeOptions: ParticipationType[] = [
  "Frosh Dorm",
  "Participated"
];
export const urlTypeOptions: UrlType[] = [
  "Digg",
  "Facebook",
  "Flickr",
  "Google",
  "Instagram",
  "LinkedIn",
  "Organization URL",
  "Other",
  "Personal Blog",
  "Personal URL",
  "Twitter",
  "Yahoo!",
  "YouTube"
];

