import {
  AdjustmentsHorizontalIcon,
  ArrowUpIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CogIcon,
  ExclamationTriangleIcon,
  HomeIcon,
  InformationCircleIcon,
  LinkIcon,
  MapPinIcon,
  LockClosedIcon as LockClosedOutlineIcon,
  EnvelopeIcon,
  PlusIcon,
  ArrowPathIcon,
  MagnifyingGlassIcon,
  UserGroupIcon,
  UserIcon,
  UserCircleIcon,
} from '@heroicons/react/24/outline';
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  LockClosedIcon,
  XMarkIcon,
  XCircleIcon,
} from '@heroicons/react/24/solid';

export const iconMap = {
  action: ChevronRightIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-up': ArrowUpIcon,
  back: ArrowLeftIcon,
  check: CheckIcon,
  'check-filled': CheckCircleIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-right': ChevronRightIcon,
  close: XMarkIcon,
  cog: CogIcon,
  dismiss: XCircleIcon,
  email: EnvelopeIcon,
  error: ExclamationCircleIcon,
  'exclamation-circle': ExclamationCircleIcon,
  external: ArrowRightIcon,
  filter: AdjustmentsHorizontalIcon,
  home: HomeIcon,
  info: InformationCircleIcon,
  jump: ChevronDownIcon,
  left: ArrowLeftIcon,
  link: LinkIcon,
  loading: ArrowPathIcon,
  location: MapPinIcon,
  lock: LockClosedIcon,
  'lock-outline': LockClosedOutlineIcon,
  search: MagnifyingGlassIcon,
  more: ArrowRightIcon,
  plus: PlusIcon,
  right: ArrowRightIcon,
  up: ArrowUpIcon,
  user: UserIcon,
  'user-circle': UserCircleIcon,
  'user-group': UserGroupIcon,
  warning: ExclamationTriangleIcon,
  'x-circle': XCircleIcon,
};

// Base size and position of each icon (finetuned manually)
// Only add to this map if different from default class su-w-1em
export const iconBaseStyle = {
  default: 'su-w-1em',
  'arrow-left': 'su-w-08em su--mt-02em',
  'arrow-right': 'su-w-08em su--mt-02em',
  back: 'su-w-1em su--mt-02em',
  'chevron-right': 'su-w-1em su--mt-4',
  email: 'su-w-08em su--mt-2',
  external: 'su-w-08em su--rotate-45 group-hover:su--rotate-45 group-focus:su--rotate-45',
  home: 'su--mt-2',
  left: 'su-w-08em su--mt-02em',
  lock: 'su-w-08em su--mt-3',
  'lock-outline': 'su-w-08em su--mt-3',
  more: 'su-w-08em su--mt-02em',
  plus: 'su-w-08em su--mt-3',
  right: 'su-w-08em su--mt-02em',
  search: 'su-w-08em',
  up: 'su-w-1em su--mt-03em',
  user: 'su-w-08em su--mt-3',
};
